sudo: required
services:
    - docker

before_install:
    - docker build -t dorairajsanjay/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true dorairajsanjay/react-test npm test -- --coverage

after_success:
    - docker build -t dorairajsanjay/multi-client ./client
    - docker build -t dorairajsanjay/multi-nginx ./nginx
    - docker build -t dorairajsanjay/multi-server ./server
    - docker build -t dorairajsanjay/multi-worker ./worker

    # Login to docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to DockerHub
    - docker push dorairajsanjay/multi-client
    - docker push dorairajsanjay/multi-nginx
    - docker push dorairajsanjay/multi-server
    - docker push dorairajsanjay/multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-141907484098
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


